apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: S3 bucket provisioning repo
spec:
  type: service
  lifecycle: experimental
  owner: ${{ values.owner }}