apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: s3-self-service
  title: S3 Self Service (Test)
  description: Test repo creation with Terraform skeleton
spec:
  owner: user:default/oskaya
  type: service

  parameters:
    - title: Bucket Info
      required:
        - name
        - owner
      properties:
        name:
          title: Bucket Name
          type: string
          description: Unique name for testing
        owner:
          title: Owner
          type: string
          ui:field: OwnerPicker
        region:
          title: AWS Region
          type: string
          default: eu-west-1

  steps:
    - id: fetch-skeleton
      name: Fetch skeleton
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: .
        values:
          name: ${{ parameters.name }}
          owner: ${{ parameters.owner }}
          region: ${{ parameters.region }}

    - id: publish-github
      name: Create GitHub repo
      action: publish:github
      input:
        allowedHosts: ["github.com"]
        repoUrl: github.com?repo=${{ parameters.name }}-s3-test&owner=oskaya
        description: "S3 provisioning repo for ${{ parameters.name }}"

  output:
    links:
      - title: GitHub Repo
        url: ${{ steps.publish-github.output.remoteUrl }}
      - title: Repo Files
        url: ${{ steps.publish-github.output.repoContentsUrl }}